speller_config:
  sentences_path: datasets/AllRu-sentences.txt.gz
  dict_path: datasets/Ildar_AllRu-freq-dict.txt.gz
  min_word_freq: 1
  min_word_length: 1
  penalty: 6.5
  unigram_weight: 1
  bigram_weight: 5
  trigram_weight: 4
  auto_train_mode: false

nats_config:
  natsAddress: "wbx-search-nats.dp.wb.ru:4222,wbx-search-nats-2.dp.wb.ru:4222,wbx-search-nats.dl.wb.ru:4222,wbx-search-nats-2.dl.wb.ru:4222"
  natsAddress2: ngx-api-r01-03.dp.wb.ru:4242,ngx-api-r02-03.dl.wb.ru:4242,ngx-api-r03-03.dl.wb.ru:4242,ngx-api-r04-03.dl.wb.ru:4242,ngx-api-r05-03.dp.wb.ru:4242
  natsAddressTest: "test-cluster"
  badSearchEventSubjectCommon: "wbxsearch.ru.exactmatch.common.badsearchevent"
  badSearchEventSubjectMale: "wbxsearch.ru.exactmatch.male.badsearchevent"
  badSearchEventSubjectFemale: "wbxsearch.ru.exactmatch.female.badsearchevent"
  badSearchEventQueryCapacity : 1024
  searchEventSubjectCommon: "wbxsearch.ru.exactmatch.common.searchevent"
  searchEventSubjectMale: "wbxsearch.ru.exactmatch.male.searchevent"
  searchEventSubjectFemale: "wbxsearch.ru.exactmatch.female.searchevent"
  searchEventQueryCapacity: 1024

s3_config:
  —ÅronForSave: "*/1 * * * *"
  s3Endpoint: "https://s3-corp-ha.wildberriessss.ru/"
  s3Region: "us-east-1"
  s3Bucket: "spellcheck"
  filePath: "./Dump/spellcheck.csv"
